const Data = [
  {
    id: 1,
    category: "education",
    icon: "icon-graduation",
    year: "Present -",
    title: "ASN — Nursing",
    desc: "Chabot College",
  },
  {
    id: 2,
    category: "education",
    icon: "icon-graduation",
    year: "Present -",
    title: "BSN — Nursing",
    desc: "California State University, East Bay",
  },
  {
    id: 3,
    category: "education",
    icon: "icon-graduation",
    year: "2014 - 2016",
    title: "Masters — Mathematics",
    desc: "California State University, East Bay",
  },
  {
    id: 4,
    category: "education",
    icon: "icon-graduation",
    year: "2010 - 2013",
    title: "Bachelors — Mathematics",
    desc: "University of California, Santa Barbara",
  },
  {
    id: 5,
    category: "experience",
    icon: "icon-briefcase",
    year: "2023 - Present",
    title: "Senior Software Engineer",
    desc: "Fastly",
  },
  {
    id: 6,
    category: "experience",
    icon: "icon-briefcase",
    year: "2020 - 2023",
    title: "Technical Lead",
    desc: "Avail Medsystems",
  },
  {
    id: 7,
    category: "experience",
    icon: "icon-briefcase",
    year: "2019 - 2020",
    title: "Lead Frontend Engineer",
    desc: "Sofar Ocean",
  },
  {
    id: 8,
    category: "experience",
    icon: "icon-briefcase",
    year: "2018 - 2019",
    title: "Software Engineer II",
    desc: "Oracle",
  },
  {
    id: 9,
    category: "experience",
    icon: "icon-briefcase",
    year: "2016 - 2018",
    title: "Frontend Engineer",
    desc: "Kaiser Permanente",
  },
];

export default Data;
